site_name: Meridian 2.0
site_description: Official documentation for the Meridian Blender to Godot addon.
site_author: Naxela

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Features:
    - Preprocessing: features/preprocessing.md
    - Lightmapping: features/lightmapping.md
    - Livelinking: features/livelinking.md
